const Words=[
  {
    word:"I",
    definition:"123",
    sentence:"fdsfsdfs"
  },
  {
    word:"to",
    definition:"123",
    sentence:"fdsfsdfs"
  },
  {
    word:"for",
    definition:"123",
    sentence:"fdsfsdfs"
  },{
    word:"they",
    definition:"123",
    sentence:"fdsfsdfs"
  },
  {
    word:"or",
    definition:"123",
    sentence:"fdsfsdfs"
 
  },
  {
    word:"can",
    definition:"123",
    sentence:"fdsfsdfs"
  },{
  word:"here",
  definition:"123",
  sentence:"fdsfsdfs"
},{
word:"see",
definition:"123",
sentence:"fdsfsdfs"
},
  {
    word:"play",
    definition:"123",
    sentence:"fdsfsdfs"
  },
  {
    word:"come",
    definition:"123",
    sentence:"fdsfsdfs"
  },
  {
    word:"the",
    definition:"123",
    sentence:"fdsfsdfs"
  },
  {
    word:"is",
    definition:"123",
    sentence:"fdsfsdfs"
  },{
    word:"are",
    definition:"123",
    sentence:"fdsfsdfs"
  },
  {
    word:"be",
    definition:"123",
    sentence:"fdsfsdfs"
 
  },
  {
    word:"one",
    definition:"123",
    sentence:"fdsfsdfs"
  },{
  word:"said",
  definition:"123",
  sentence:"fdsfsdfs"
},{
word:"like",
definition:"123",
sentence:"fdsfsdfs"
},
  {
    word:"my",
    definition:"123",
    sentence:"fdsfsdfs"
  },
  {
    word:"this",
    definition:"123",
    sentence:"fdsfsdfs"
  },{
  word:"help",
  definition:"123",
  sentence:"fdsfsdfs"
},{
word:"of",
definition:"123",
sentence:"fdsfsdfs"
},
  {
    word:"you",
    definition:"123",
    sentence:"fdsfsdfs"
  },

  {
    word:"as",
    definition:"123",
    sentence:"fdsfsdfs"
 
  },
  {
    word:"does",
    definition:"123",
    sentence:"fdsfsdfs"
  },{
  word:"by",
  definition:"123",
  sentence:"fdsfsdfs"
},{
word:"she",
definition:"123",
sentence:"fdsfsdfs"
},
  {
    word:"has",
    definition:"123",
    sentence:"fdsfsdfs"
  },
  {
    word:"good",
    definition:"123",
    sentence:"fdsfsdfs"
  },{
  word:"little",
  definition:"123",
  sentence:"fdsfsdfs"
},{
word:"and",
definition:"123",
sentence:"fdsfsdfs"
},
  {
    word:"he",
    definition:"123",
    sentence:"fdsfsdfs"
  },


  {
    word:"with",
    definition:"123",
    sentence:"fdsfsdfs"
  },{
  word:"have",
  definition:"123",
  sentence:"fdsfsdfs"
},{
word:"what",
definition:"123",
sentence:"fdsfsdfs"
},
  {
    word:"do",
    definition:"123",
    sentence:"fdsfsdfs"
  },
  {
    word:"look",
    definition:"123",
    sentence:"fdsfsdfs"
  },{
  word:"where",
  definition:"123",
  sentence:"fdsfsdfs"
},{
word:"me",
definition:"123",
sentence:"fdsfsdfs"
},
  {
    word:"a",
    definition:"123",
    sentence:"fdsfsdfs"
  },
  {
    word:"was",
    definition:"123",
    sentence:"fdsfsdfs"
  },{
  word:"his",
  definition:"123",
  sentence:"fdsfsdfs"
},{
word:"from",
definition:"123",
sentence:"fdsfsdfs"
},
  {
    word:"we",
    definition:"123",
    sentence:"fdsfsdfs"
  },
  {
    word:"want",
    definition:"123",
    sentence:"fdsfsdfs"
  },{
  word:"go",
  definition:"123",
  sentence:"fdsfsdfs"
},{
word:"who",
definition:"123",
sentence:"fdsfsdfs"
},
  {
    word:"too",
    definition:"123",
    sentence:"fdsfsdfs"
  },
]


export default Words;